spring.datasource.url=jdbc:h2:file:./data/flexispace;DB_CLOSE_DELAY=-1;AUTO_SERVER=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
server.port=8081
jwt.secret=mySuperSecretKeyForJwtAuthenticationWhichIsVeryLongAndSecure123!
app.cors.allowed-origins=http://localhost:5173
